### ISSUE TITLE
assets are missing.

### ISSUE THREAD

**Issue by EssenOH** [hooyuser/TextureNodes#1]
under /assets, there are no files such as .png, obj, exr and so on... then the it can't create textures.

**Comment by EssenWorkbench** [comment]
Missing assets under the directory /assets such as .hdr, .exr, .png and .obj files.

**Comment by hooyuser** [comment]
Thank you for reporting this problem. Now I use git lfs to track these assets. You can get access to them by `git clone` with git lfs installed on your device.

**Comment by EssenOH** [comment]
Thanks for quick updating the assets, still one directory is missing.
skyBoxObject.mesh = Mesh::load_from_obj(this,
"assets/obj_models/skybox.obj");

**Comment by hooyuser** [comment]
Update obj_models. My assets directory is still a little messy. I'll clean them up later.

**Comment by EssenOH** [comment]
wonderful!... now the program is finally running on.

**Comment by hooyuser** [comment]
Glad to hear that :)
